### PR TITLE
create and update categories and origins

### PR DESCRIPTION
**Pull request by mjl2256**
changed the routes from /update and /create to /update/dog, /update/origin, /update/category, /create/dog, /create/origin, /create/category

### CODE REVIEW

**Comment by mjl2256** [comment]
added /sizes, /sizes/:id, /update/size, /create/size

**Comment by hsingwenhsu** [comment]
1. Need to add nodemon.json to .gitignore to protect the password.
2. There seems to be no error checking for the `name` parameter of the `update_metadata ` function in controller/update.js. If we make an update request with no name specified, the server will still return the unchanged object. No error is thrown and no update is made. So I just want to make sure if this is the intended behavior.

**Comment by mjl2256** [comment]
1. If we remove nodemon.json from the repo, we'll need to use one of the AWS secrets management services to get the info, right?
2. Now explicitly throws error for empty name in an update call

**Comment by hsingwenhsu** [comment]
Yes, we will need to set up the environment variable within AWS.

**Pull request merged**
